"""add system_settings

Revision ID: 2a68057de53b
Revises: 081ea1895159
Create Date: 2025-12-10 22:03:07.687175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a68057de53b'
down_revision: Union[str, Sequence[str], None] = '081ea1895159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('department_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_maps_id'), 'maps', ['id'], unique=False)
    op.create_index(op.f('ix_zones_id'), 'zones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zones_id'), table_name='zones')
    op.drop_index(op.f('ix_maps_id'), table_name='maps')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
